name: build and publish web docker release

on:
  workflow_dispatch:
  push:
    tags:
      - "web-v*"

jobs:
  publish-server-docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: get the tag name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: checkout upstream code
        uses: actions/checkout@v4
        with:
          path: upstream-code
          repository: "ente-io/ente"
          ref: ${{ steps.get_tag.outputs.TAG }}

      - name: checkout code
        uses: actions/checkout@v4
        with:
          path: code

      - name: copy custom web dir to upstream dir
        run: cp -r code/web/* upstream-code/web

      - name: fetch git submodules
        run: cd upstream-code/web && git submodule update --init --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ secrets.GH_USERNAME }}/ente-web:latest
            ghcr.io/${{ secrets.GH_USERNAME }}/ente-web:${{ steps.get_tag.outputs.TAG }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: upstream-code/web
          file: upstream-code/web/Dockerfile
